DROP TABLE IF EXISTS Book;


CREATE TABLE IF NOT EXISTS Book
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(200) NOT NULL,
    author          VARCHAR(200) NOT NULL,
    published_date  DATE NOT NULL
);
